In [27]:
# 1.Create a 2D NumPy array (10×5) with random integers (1–100).
import numpy as np

arr = np.random.randint(1, 101, (10, 5))
print(arr)

[[ 86  89  43  64  46]
 [ 66  18  85  45  92]
 [ 23  62  44  36  21]
 [ 42  69  33  17  24]
 [ 71  27  70  25  34]
 [  3  32  70  50  49]
 [ 49  30  94  84  53]
 [ 87 100  67   9  19]
 [ 21  55  46  93  47]
 [ 75  59  98  82  38]]


In [28]:
# 2. Replace all values < 50 with 0 and ≥ 50 with 1.
binary_arr = np.where(arr < 50, 0, 1)
print(binary_arr)
 

[[1 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [0 1 0 1 0]
 [1 1 1 1 0]]


In [29]:
# 3. Compute mean, standard deviation, variance along rows and columns.
row_mean = arr.mean(axis=1)
col_mean = arr.mean(axis=0)

row_std = arr.std(axis=1)
col_std = arr.std(axis=0)

row_var = arr.var(axis=1)
col_var = arr.var(axis=0)

In [30]:
# 4. Generate two arrays A(3×3) and B(3×3) and perform matrix multiplication.
A = np.random.randint(1, 10, (3,3))
B = np.random.randint(1, 10, (3,3))

result = A @ B
print(result)

[[ 49  93 106]
 [ 52 106 114]
 [ 38  80  74]]


In [31]:
# 5. Find the eigenvalues and eigenvectors of a 3×3 matrix.
vals, vecs = np.linalg.eig(A)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)

Eigenvalues: [20.75328502 -1.33793076  1.58464574]
Eigenvectors:
 [[-0.58673911 -0.78462968 -0.12847779]
 [-0.67584922  0.22219613 -0.78773749]
 [-0.44605499  0.57877901  0.60246419]]


In [32]:
# 6. Create a 1D array of 100 random values and normalize it (0–1 scale).
arr1d = np.random.rand(100)
norm = (arr1d - arr1d.min()) / (arr1d.max() - arr1d.min())

In [33]:
# 7. Stack two arrays vertically and horizontally.
x = np.array([1,2,3])
y = np.array([4,5,6])

vstack = np.vstack((x,y))
hstack = np.hstack((x,y))

In [34]:
# 8. Create an array of shape (5,5) and extract the diagonal, upper triangle and lower triangle.
m = np.random.randint(1, 20, (5,5))

diag = np.diag(m)
upper = np.triu(m)
lower = np.tril(m)

In [35]:
# 9. Generate a 4×4 array and compute its determinant and inverse.
mat = np.random.randint(1, 10, (4,4))

det = np.linalg.det(mat)
inv = np.linalg.inv(mat)

In [36]:
# 10. Write a NumPy program to perform element-wise comparison between two equal-sized arrays.
a = np.array([1,2,3])
b = np.array([3,2,1])

print(a == b)
print(a > b)
print(a < b)

[False  True False]
[False False  True]
[ True False False]


In [37]:
# 11. Create a 1000-element array and compute: 25th percentile, 50th percentile, 75th percentile
big = np.random.rand(1000)

p25 = np.percentile(big, 25)
p50 = np.percentile(big, 50)
p75 = np.percentile(big, 75)

In [42]:
# 12. Reshape a 1D array into 3 possible valid shapes.
r = np.arange(12)

shape1 = r.reshape(3, 4)
shape2 = r.reshape(4, 3)
shape3 = r.reshape(2, 6)

In [43]:
# 13. Perform broadcasting on two arrays of shapes (5,1) and (1,5).
a = np.arange(5).reshape(5,1)
b = np.arange(5).reshape(1,5)

broadcast_result = a + b    # auto-expands

In [44]:
# 14. Create a boolean mask to filter values > mean + std from an array.
arr = np.random.randint(1, 100, 50)

threshold = arr.mean() + arr.std()
mask = arr > threshold

filtered = arr[mask]