In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.4'

In [4]:
a = np.array([2, 3, 4])
print(a)
a.dtype

[2 3 4]


dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [6]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
np.empty((2, 3))

array([[ 2.12199579e-314, -1.18570984e-051,  1.18175599e-311],
       [ 1.18175599e-311,  9.38724727e-323,  1.11253693e-308]])

In [14]:
print(np.arange(10, 30, 5))
np.arange(0, 2, 0.3)

[10 15 20 25]


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [17]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
print(a)
c = a - b
print(c)
b**2

[0 1 2 3]
[20 30 40 50]
[20 29 38 47]


array([0, 1, 4, 9])

In [26]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)    # elementwise product

print(A @ B)    # matrix product

print(A.dot(B))  # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [31]:
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1.])
print(np.add(B, C))

[[ 7.3890561   1.        ]
 [20.08553692 54.59815003]]
[[1.41421356 0.        ]
 [1.73205081 2.        ]]
[[ 4. -1.]
 [ 5.  3.]]


In [34]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]


In [35]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [36]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [38]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [45]:
random = np.random.randint(1,10,5)
print(random)

[7 7 6 9 5]


In [50]:
a = np.array([4, 2])
b = np.array([3, 8])
print(np.hstack((a, b)))
print(np.vstack((a,b)))


[4 2 3 8]
[[4 2]
 [3 8]]


In [51]:
a = np.array([[5, 6], [7, 8]])
res = a.flatten()
print(res)

[5 6 7 8]


In [52]:
np.transpose(a)

array([[5, 7],
       [6, 8]])

In [56]:
# Indexing with arrays of indices
a = np.arange(12)**2  # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])  # an array of indices
print(a[i])
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
print(a[j])  # the same shape as `j`


[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [57]:
a = np.arange(5)
print(a)
a[[1, 3, 4]] = 0
print(a)


[0 1 2 3 4]
[0 0 2 0 0]


In [59]:
a = np.arange(12).reshape(3, 4)
print(a)
b = a > 4
print(b) # `b` is a boolean with `a`'s shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
